BEGIN;
DROP DATABASE IF EXISTS brief_morphee;
CREATE DATABASE brief_morphee;
USE brief_morphee;

CREATE TABLE "HOTEL" (
  "HOTEL_ID" integer PRIMARY KEY,
  "ENSEIGNE_ID" int,
  "PAYS_ID" int,
  "ZONE_GEOGRAPHIQUE_ID" int,
  "nom" VARCHAR,
  "nombre_etoiles" INTEGER,
  "descriptif" TEXT,
  "numero_voie" INTEGER,
  "type_voie" VARCHAR,
  "nom_voie" VARCHAR,
  "code_postal" INTEGER,
  "ville" VARCHAR
);

CREATE TABLE "PAYS" (
  "PAYS_ID" VARCHAR PRIMARY KEY,
  "nom" VARCHAR
);

CREATE TABLE "SAISONNALITE" (
  "SAISONNALITE_ID" integer PRIMARY KEY,
  "ZONE_GEOGRAPHIQUE_ID" int,
  "saison" VARCHAR,
  "date_debut" DATE,
  "date_fin" DATE
);

CREATE TABLE "ZONE_GEOGRAPHIQUE" (
  "ZONE_GEOGRAPHIQUE_ID" integer PRIMARY KEY,
  "nom" VARCHAR
);

CREATE TABLE "ENSEIGNE" (
  "ENSEIGNE_ID" integer PRIMARY KEY,
  "nom" VARCHAR
);

CREATE TABLE "CHAMBRE" (
  "CHAMBRE_ID" integer PRIMARY KEY,
  "HOTEL_ID" int,
  "niveau_confort" VARCHAR,
  "nombre_lits" INTEGER
);

CREATE TABLE "CLIENT" (
  "CLIENT_ID" integer PRIMARY KEY,
  "SIRET" int,
  "CHAMBRE_ID" int,
  "nom" VARCHAR,
  "prenom" VARCHAR,
  "numero_cb" INTEGER,
  "numero_telephone" INTEGER,
  "email" VARCHAR,
  "date_naissance" DATE
);

CREATE TABLE "DOSSIER_CLIENT_PRO" (
  "SIRET" integer PRIMARY KEY,
  "nom" VARCHAR,
  "numero_voie" INTEGER,
  "type_voie" VARCHAR,
  "nom_voie" VARCHAR,
  "code_postal" INTEGER,
  "ville" VARCHAR
);

CREATE TABLE "RESERVATION" (
  "RESERVATION_ID" integer PRIMARY KEY,
  "CLIENT_ID" int,
  "CHAMBRE_ID" int,
  "date_debut" DATE,
  "duree_sejour" INTEGER
);

CREATE TABLE "FACTURATION" (
  "FACTURATION_ID" integer PRIMARY KEY,
  "RESERVATION_ID" int,
  "LISTE_OPTION_ID" int,
  "date_facture" DATE,
  "date_debut_effectif" DATE,
  "duree_sejour_effectif" INTEGER,
  "niveau_confort_chambre_effectif" VARCHAR,
  "reduction_eventuelle" INTEGER,
  "montant" INTEGER,
  "devise" VARCHAR
);

CREATE TABLE "LISTE_OPTION" (
  "LISTE_OPTION_ID" integer PRIMARY KEY,
  "nom" VARCHAR,
  "prix" INTEGER
);

ALTER TABLE "HOTEL" ADD FOREIGN KEY ("ENSEIGNE_ID") REFERENCES "ENSEIGNE" ("ENSEIGNE_ID");

ALTER TABLE "HOTEL" ADD FOREIGN KEY ("PAYS_ID") REFERENCES "PAYS" ("PAYS_ID");

ALTER TABLE "HOTEL" ADD FOREIGN KEY ("ZONE_GEOGRAPHIQUE_ID") REFERENCES "ZONE_GEOGRAPHIQUE" ("ZONE_GEOGRAPHIQUE_ID");

ALTER TABLE "SAISONNALITE" ADD FOREIGN KEY ("ZONE_GEOGRAPHIQUE_ID") REFERENCES "ZONE_GEOGRAPHIQUE" ("ZONE_GEOGRAPHIQUE_ID");

ALTER TABLE "CHAMBRE" ADD FOREIGN KEY ("HOTEL_ID") REFERENCES "HOTEL" ("HOTEL_ID");

ALTER TABLE "CLIENT" ADD FOREIGN KEY ("SIRET") REFERENCES "DOSSIER_CLIENT_PRO" ("SIRET");

ALTER TABLE "CLIENT" ADD FOREIGN KEY ("CHAMBRE_ID") REFERENCES "CHAMBRE" ("CHAMBRE_ID");

ALTER TABLE "RESERVATION" ADD FOREIGN KEY ("CLIENT_ID") REFERENCES "CLIENT" ("CLIENT_ID");

ALTER TABLE "RESERVATION" ADD FOREIGN KEY ("CHAMBRE_ID") REFERENCES "CHAMBRE" ("CHAMBRE_ID");

ALTER TABLE "FACTURATION" ADD FOREIGN KEY ("RESERVATION_ID") REFERENCES "RESERVATION" ("RESERVATION_ID");

ALTER TABLE "FACTURATION" ADD FOREIGN KEY ("LISTE_OPTION_ID") REFERENCES "LISTE_OPTION" ("LISTE_OPTION_ID");
